apiVersion: v1 
kind: Pod
metadata:
  name: multiple
spec:
  containers:
    - image: nginx:1.14.2
      name: nginx
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "150m"
          memory: "200Mi"
        limits:
          cpu: "200m"
          memory: "300Mi"
    - image: almalinux
      name: sidecar
      command: ["sleep", "200"]
      resources:
        requests:
          cpu: "150m"
          memory: "200Mi"
        limits:
          cpu: "200m"
          memory: "300Mi"