apiVersion: v1 
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - image: nginx:1.14.2
      name: nginx
      imagePullPolicy: Always
      resources:
        requests:
          cpu: "150m"
          memory: "200Mi" 
        limits:
          cpu: "150m"
          memory: "300Mi"
          