apiVersion: v1 
kind: Pod
metadata:
  name: probe
spec:
  containers:
    - image: nginx:1.14.2
      name: nginx
      ports:
        - containerPort: 80
      imagePullPolicy: Always
      resources:
        requests:
          cpu: "150m"
          memory: "200Mi"
        limits:
          cpu: "200m"
          memory: "300Mi"
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 3
        periodSeconds: 3
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 3
        periodSeconds: 3
        