apiVersion: v1 
kind: Pod
metadata:
  name: label-pod
  labels:
    course: docker
    duration: 25hr
    trainer: siva
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "150m"
          memory: "200Mi"
        limits:
          cpu: "200m"
          memory: "300Mi"
