apiVersion: v1 
kind: Pod
metadata:
  name: envars-demo
  labels:
    purpose: demonstrate-envars
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      imagePullPolicy: Always
      env:
        - name: course
          value: docker
        - name: trainer
          value: siva
      resources:
        requests:
          cpu: "250m"
          memory: "64Mi"
        limits:
          cpu: "500m"
          memory: "128Mi"
        
