apiVersion: v1 
kind: Pod
metadata:
  name: config-pod
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      imagePullPolicy: Always
      envFrom:
        - configMapRef:
            name: course-config
      resources:
        requests:
          cpu: "250m"
          memory: "64Mi"
        limits:
          cpu: "500m"
          memory: "128Mi"
      ports:
        - containerPort: 80