apiVersion: v1 
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      imagePullPolicy: Always
      resources:
        requests:
          cpu: "250m"
          memory: "64Mi"
        limits:
          cpu: "500m"
          memory: "128Mi"
      env:
        - name: USERNAME 
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name: PASSWORD 
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password