---
apiVersion: v1 
kind: Pod
metadata:
  name: nginx
  labels:
    server: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
---
apiVersion: v1 
kind: Service 
metadata:
  name: nginx-service
spec:
  selector:
    server: nginx
  ports:
    - protocal: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1 
kind: Pod
metadata:
  name: debug
  labels:
    purpose: debug
spec:
  containers:
    - name: almalinux
      image: almalinux
      command: ["sleep","100000"]
---
