---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-ebs-dynamic-pvc
spec:
  storageClassName: ebs-sc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 14Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      imagepullpolicy: always
      ports:
      - containerPort: 80
      imagePullPolicy: Always
      resources:
        requests:
          cpu: "150m"
          memory: "200Mi"
        limits:
          cpu: "200m"
          memory: "300Mi"
      volumeMounts:
        - name: my-ebs-volume
          mountPath: /usr/share/nginx/html
  volume:
    - name: my-ebs-volume
      persistentVolumeClaim:
        claimName: my-ebs-dynamic-pvc
---